# Site settings
title: "notes/logs/labs"
description: "raw material"
baseurl: ""
url: ""
author: ""

#footer-links:
# github: xvag
# twitter: xvag

# Build settings
kramdown:
  input: GFM
permalink: pretty

