# Site settings
title: "notes/logs/labs"
description: "raw material"
baseurl: ""
url: ""
author: ""

# Build settings
kramdown:
  input: GFM
permalink: pretty

plugins:
 - jekyll-relative-links

relative_links:
 enabled: true
