# Site settings
title: "notes/logs/labs"
description: ""
baseurl: ""
url: ""
author: ""

# Footer
#footer-links:
# github: xvag
# twitter: xvag

# Build settings
kramdown:
  input: GFM
permalink: pretty

